apiVersion : apps/v1
kind: Deployment
metadata:
  name: "docshareaks-4363"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "docshareaks-4363"
  template:
    metadata:
      labels:
        app: "docshareaks-4363"
    spec:
      containers:
        - name: "docshareaks-4363"
          image: "entregasdevops.azurecr.io/docshareaks"
          ports:
          - containerPort: 43