apiVersion: v1
kind: Service
metadata:
    name: "docshareaks-4363"
    labels:
        app: "docshareaks-4363"
spec:
    type: LoadBalancer
    ports:
    - port: 43
      targetPort: 43
      protocol: TCP
      name: http
    selector:
        app: "docshareaks-4363"